// styles/emotionStyles.ts
// Generated by conversion: exports for all previously global CSS classes

import { css, keyframes } from "@emotion/css";

export const header = css`
  background: white;
  padding: 1rem 1.5rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.06);
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: sticky;
  top: 0;
  z-index: 100;
`;

export const headerTitle = css`
  font-size: 1.25rem;
  color: #333;
`;

export const cartButton = css`
  position: relative;
  background: #185ea9ff;
  color: white;
  padding: 0.6rem;
  border-radius: 50%;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
`;

export const cartButtonHover = css``;

export const cartBadge = css`
  position: absolute;
  top: -6px;
  right: -6px;
  background: #dc3545;
  color: white;
  border-radius: 50%;
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.75rem;
  font-weight: bold;
`;

export const mainContent = css`
  padding: 1.5rem;
`;

export const searchBar = css`
  background: white;
  padding: 0.8rem;
  border-radius: 8px;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 1.25rem;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.06);
`;

export const searchInput = css`
  flex: 1;
  border: none;
  outline: none;
  font-size: 1rem;
`;

export const clearFiltersBtn = css`
  background: none;
  border: none;
  color: #007bff;
  cursor: pointer;
`;

export const contentWrapper = css`
  display: flex;
  gap: 1rem;
  align-items: flex-start;
`;

/* Filters */
export const filters = css`
  background: white;
  padding: 1rem;
  border-radius: 8px;
  min-width: 220px;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.06);
`;

export const filtersMobile = css`
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  border-radius: 12px 12px 0 0;
  z-index: 60;
  background: lightgray;
`;

export const filterToggle = css`
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: #007bff;
  color: white;
  border: none;
  padding: 0.8rem;
  border-radius: 12px 12px 0 0;
  cursor: pointer;
`;

export const filterRotate = css`
  transform: rotate(180deg);
`;

export const filterContent = css`
  display: block;
`;

export const filterGroup = css`
  margin-bottom: 1rem;
`;

export const filterHeading = css`
  margin-bottom: 0.5rem;
  font-size: 0.95rem;
  color: #333;
`;

export const filterInput = css`
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #eee;
  border-radius: 6px;
`;

export const priceInputs = css`
  display: flex;
  align-items: center;
  gap: 0.5rem;
`;

/* Product grid */
export const productListing = css`
  flex: 1;
  height: calc(100vh - 220px);
  overflow-y: auto;
`;

export const productGrid = css`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 1rem;
`;

/* Product card */
export const productCard = css`
  background: white;
  border-radius: 8px;
  padding: 0.9rem;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.06);
  transition: transform 0.18s, box-shadow 0.18s;
  &:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.08);
  }
`;

export const productImageContainer = css`
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 0.6rem;
  position: relative;
  // overflow: hidden;
  padding: 4px;
`;

export const productImage = css`
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
  opacity: 0;
  transition: opacity 0.2s;
`;

export const productImageLoaded = css`
  opacity: 1;
`;

export const productTitle = css`
  font-size: 0.9rem;
  margin-bottom: 0.4rem;
  height: 2.6em;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 2; /* show only 2 lines */
  -webkit-box-orient: vertical;
  text-overflow: ellipsis;
  white-space: normal;
`;
export const productPrice = css`
  font-size: 1.1rem;
  font-weight: 700;
  color: #007bff;
  margin-bottom: 0.6rem;
`;

export const addToCartBtn = css`
  width: 100%;
  background: #007bff;
  color: white;
  border: none;
  padding: 0.6rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 600;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  &:hover {
    background: #0056b3;
  }
`;
export const addToCartBtnDisabled = css`
  background: #7d6c6fff;
  cursor: not-allowed;
`;

/* Skeleton */
export const skeleton = css`
  animation: pulse 1.4s ease-in-out infinite;
`;

export const pulse = keyframes`
  0%,100%{opacity:1}
  50%{opacity:0.5}
`;

export const skeletonImage = css`
  width: 100%;
  height: 180px;
  background: #e6e6e6;
  border-radius: 6px;
  margin-bottom: 0.6rem;
`;

export const skeletonText = css`
  height: 12px;
  background: #e6e6e6;
  border-radius: 6px;
  margin-bottom: 6px;
`;

export const skeletonTextShort = css`
  width: 60%;
`;

export const skeletonButton = css`
  height: 38px;
  background: #e6e6e6;
  border-radius: 6px;
`;

/* Cart drawer */
export const cartOverlay = css`
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.2s;
  z-index: 999;
`;

export const cartOverlayOpen = css`
  opacity: 1;
  pointer-events: auto;
`;

export const cartDrawer = css`
  position: fixed;
  top: 0;
  right: -420px;
  width: 400px;
  max-width: 92vw;
  height: 100vh;
  background: white;
  box-shadow: -2px 0 12px rgba(0, 0, 0, 0.08);
  transition: right 0.25s;
  z-index: 1000;
  display: flex;
  flex-direction: column;
`;

export const cartDrawerOpen = css`
  right: 0;
`;

export const cartHeader = css`
  padding: 1rem;
  border-bottom: 1px solid #f0f0f0;
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

export const cartItems = css`
  flex: 1;
  overflow-y: auto;
  padding: 1rem;
`;

export const emptyCart = css`
  text-align: center;
  color: #888;
  padding: 2rem;
`;

export const cartItem = css`
  display: flex;
  gap: 0.8rem;
  padding: 0.8rem 0;
  border-bottom: 1px solid #f8f8f8;
`;

export const cartItemImg = css`
  width: 72px;
  height: 72px;
  object-fit: contain;
`;

export const cartItemDetails = css`
  flex: 1;
`;

export const cartItemTitle = css`
  font-size: 0.9rem;
  margin-bottom: 0.3rem;
`;

export const cartItemPrice = css`
  color: #007bff;
  font-weight: 700;
  margin-bottom: 0.3rem;
`;

export const quantityControls = css`
  display: flex;
  align-items: center;
  gap: 0.5rem;
`;

export const quantityButton = css`
  background: #f2f2f2;
  border: none;
  width: 28px;
  height: 28px;
  border-radius: 6px;
  cursor: pointer;
`;

export const removeBtn = css`
  margin-left: auto;
  color: #dc3545 !important;
`;

export const cartFooter = css`
  padding: 1rem;
  border-top: 1px solid #f0f0f0;
`;

export const cartTotal = css`
  display: flex;
  justify-content: space-between;
  margin-bottom: 0.6rem;
  font-size: 1.1rem;
`;

export const checkoutBtn = css`
  width: 100%;
  background: #28a745;
  color: white;
  border: none;
  padding: 1rem;
  border-radius: 4px;
  cursor: pointer;
  font-weight: 600;
  font-size: 1rem;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
`;

export const checkoutBtnDisabled = css`
  background: #6c757d;
  cursor: not-allowed;
`;

export const checkoutSuccess = css`
  color: #28a745;
  text-align: center;
  margin-top: 0.5rem;
  font-weight: 600;
`;

export const checkoutError = css`
  color: #dc3545;
  text-align: center;
  margin-top: 0.5rem;
  font-weight: 600;
`;

export const spin = keyframes`
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
`;

export const spinAnimation = css`
  animation: ${spin} 1s linear infinite;
`;

export const noResults = css`
  text-align: center;
  color: #888;
  padding: 2rem;
`;

/* product detail */

/* responsive */
export const responsive = css`
  @media (max-width: 768px) {
    .contentWrapper {
      flex-direction: column;
    }
  }
`;

export const detailContainer = css`
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
`;

export const productDetail = css`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  margin-top: 2rem;

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
    gap: 2rem;
  }
`;

export const detailLeft = css`
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
`;

export const detailImage = css`
  max-width: 100%;
  max-height: 500px;
  width: auto;
  height: auto;
  object-fit: contain;
`;

export const detailRight = css`
  display: flex;
  flex-direction: column;
  gap: 1rem;

  h1 {
    font-size: 2rem;
    font-weight: 600;
    color: #1a1a1a;
    margin: 0;
    line-height: 1.3;
  }
`;

export const detailCategory = css`
  display: inline-block;
  padding: 0.25rem 0.75rem;
  background: #f0f0f0;
  border-radius: 4px;
  font-size: 0.875rem;
  font-weight: 500;
  color: #666;
  text-transform: capitalize;
  width: fit-content;
`;

export const detailPrice = css`
  font-size: 2rem;
  font-weight: 700;
  color: #2563eb;
  margin: 0.5rem 0;
`;

export const detailDesc = css`
  font-size: 1rem;
  line-height: 1.6;
  color: #4a4a4a;
  margin: 1rem 0;
`;

export const buttonGroup = css`
  display: flex;
  gap: 12px;
  margin-top: 16px;

  @media (max-width: 480px) {
    flex-direction: column;
  }
`;

export const secondaryBtn = css`
  padding: 0.75rem 1.5rem;
  background: #fff;
  border: 2px solid #e5e5e5;
  border-radius: 6px;
  font-size: 1rem;
  font-weight: 500;
  color: #666;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    border-color: #2563eb;
    color: #2563eb;
    background: #f0f7ff;
  }

  &:active {
    transform: scale(0.98);
  }
`;

// Animation for page load
export const fadeIn = keyframes`
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
`;

export const animatedDetail = css`
  animation: ${fadeIn} 0.4s ease-out;
`;

export const nav = css`
  display: flex;
  gap: 0.6rem;
  margin-left: 1rem;
  align-items: center;
`;

export const navLink = css`
  text-decoration: none;
  padding: 0.45rem 0.6rem;
  border-radius: 0.45rem;
  font-size: 0.95rem;
  color: rgba(0, 0, 0, 0.75);
  transition: background 120ms ease, color 120ms ease;
  &:hover {
    background: rgba(0, 0, 0, 0.03);
  }
`;

export const navLinkActive = css`
  background: rgba(0, 0, 0, 0.06);
  color: black;
  font-weight: 600;
`;

export const pageChangeBanner = css`
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  bottom: -1.6rem;
  background: #111827;
  color: white;
  padding: 0.25rem 0.7rem;
  border-radius: 0.45rem;
  font-size: 0.85rem;
  box-shadow: 0 6px 18px rgba(0, 0, 0, 0.12);
`;

export const footerContainer = css`
  width: 100%;
  padding: 1rem;
  border-top: 1px solid rgba(0, 0, 0, 0.04);
  background: #ffffff;
  display: flex;
  justify-content: center;
  align-items: center;
`;

export const footerText = css`
  font-size: 0.9rem;
  color: rgba(0, 0, 0, 0.6);
`;
export const growOverflow = css`
  flex-grow: 1;
  overflow: hidden;
`;
export const tooltipWrapper = css`
  position: relative;
  display: inline-flex;
  cursor: help;
`;

export const tooltipBox = css`
  position: absolute;
  bottom: 120%;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  color: #fff;
  padding: 0.4rem 0.7rem;
  font-size: 0.75rem;
  border-radius: 4px;
  white-space: nowrap;
  z-index: 999;
  transition: opacity 0.2s ease-in-out;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);

  &::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    transform: translateX(-50%);
    border-width: 6px;
    border-style: solid;
    border-color: #111 transparent transparent transparent;
  }
`;